global:
  nodeSelector: {}
  affinity: {}
  tolerations: {}

replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmniindiadistro
  name: hiu
  tag: latest

service:
  type: ClusterIP
  port: 9053

config:
  IDENTITY_JWK_URL: "https://dev.ndhm.gov.in/auth/realms/consent-manager/protocol/openid-connect/certs"
  DATA_PUSH_URL: ""
  CONSENT_NOTIFICATION_URL: "http://localhost:8003/consent/notification"
  CONSENT_MANAGEMENT_SUFFIX: "@sbx"
  CONSENT_MANAGEMENT_URL: "https://dev.ndhm.gov.in/cm"
  DEFAULT_PAGE_SIZE: 20
  MAX_PAGE_SIZE: 100
  LOCAL_STORAGE_PATH: "/tmp/"
  POSTGRES_HOST: bahmni-dev-postgresql
  POSTGRES_PORT: 5432
  CONSENT_MANAGER_DB_NAME: "health_information_user"
  DB_CONNECTION_POOL_SIZE: 5
  OFFSET_IN_DAYS: 2
  USING_GATEWAY: true
  GATEWAY_BASE_URL: "https://dev.abdm.gov.in/gateway/v0.5"
  GATEWAY_REQUEST_TIMEOUT: 3000
  GATEWAY_JWK_URL: "https://dev.abdm.gov.in/gateway/v0.5/certs"
  HFR_AFFINITY_DOMAINS: "facilitysbx.ndhm.gov.in"
  RABBITMQ_HOST: bahmni-dev-rabbitmq
  RABBITMQ_PORT: 5672
  MAX_IN_MEMORY_SIZE: 500MB
  DATA_FLOW_CONSENT_REQUEST_WAIT_TIME: 1
  DATA_FLOW_CONSENT_ARTEFACT_WAIT_TIME: 1
  DATA_FLOW_PART_WAIT_TIME: 1440
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "welcome"
  RABBITMQ_USERNAME: "bahmni"
  RABBITMQ_PASSWORD: "bahmni"

secrets:
  HIU_CLIENT_ID: ""
  HIU_CLIENT_SECRET: ""


autoscaling:
  enabled: false

nodeSelector: {}
affinity: {}
tolerations: {}
